personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

[windows]
sandbox = "unelevated"

[projects.'C:\Users\24228']
trust_level = "trusted"

[projects.'C:\Users\24228\Desktop\ai-auto-deepstremth']
trust_level = "trusted"

[projects.'C:\Users\24228\.codex']
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
